spring:
  application:
    name: account
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

security:
  oauth2:
    client:
      clientId: account
      clientSecret: 123456
      grantType: client_credentials
#      accessTokenUri: http://localhost:8082/authx-server/oauth/token
#      userAuthorizationUri: http://localhost:8082/authx-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8082/authx-server/userInfo

server:
  port: 8083
  servlet:
    contextPath: /account