server:
  port: 8082
  servlet:
    contextPath: /authx-server

spring:
  application:
    name: authx-server
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=3d

security:
  oauth2:
    client:
      client-id: account
      client-secret: 123456